[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.13"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.deploy]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.13"
optimizer = true
optimizer_runs = 200 